package com.ravi.mylivetv.utils

object CategoryMapper {
    
    // Maps display names to URL-compatible category names
    private val categoryMap = mapOf(
        "Auto" to "auto",
        "Animation" to "animation",
        "Business" to "business",
        "Classic" to "classic",
        "Comedy" to "comedy",
        "Cooking" to "cooking",
        "Culture" to "culture",
        "Documentary" to "documentary",
        "Education" to "education",
        "Entertainment" to "entertainment",
        "Family" to "family",
        "General" to "general",
        "Kids" to "kids",
        "Legislative" to "legislative",
        "Lifestyle" to "lifestyle",
        "Movies" to "movies",
        "Music" to "music",
        "News" to "news",
        "Outdoor" to "outdoor",
        "Relax" to "relax",
        "Religious" to "religious",
        "Series" to "series",
        "Science" to "science",
        "Shop" to "shop",
        "Sports" to "sports",
        "Travel" to "travel",
        "Weather" to "weather"
    )
    
    // Maps display language names to language codes
    private val languageMap = mapOf(
        "Albanian" to "sqi",
        "Amharic" to "amh",
        "Arabic" to "ara",
        "Armenian" to "hye",
        "Assamese" to "asm",
        "Assyrian Neo-Aramaic" to "aii",
        "Azerbaijani" to "aze",
        "Bashkir" to "bak",
        "Basque" to "eus",
        "Belarusian" to "bel",
        "Bengali" to "ben",
        "Bosnian" to "bos",
        "Bulgarian" to "bul",
        "Burmese" to "mya",
        "Catalan" to "cat",
        "Chinese" to "zho",
        "Croatian" to "hrv",
        "Czech" to "ces",
        "Danish" to "dan",
        "Dhivehi" to "div",
        "Dimili" to "zza",
        "Dutch" to "nld",
        "English" to "eng",
        "Estonian" to "est",
        "Faroese" to "fao",
        "Fataleka" to "far",
        "Finnish" to "fin",
        "French" to "fra",
        "Galician" to "glg",
        "Galolen" to "gal",
        "Georgian" to "kat",
        "German" to "deu",
        "Greek" to "ell",
        "Greenlandic" to "kal",
        "Gujarati" to "guj",
        "Hebrew" to "heb",
        "Hindi" to "hin",
        "Hungarian" to "hun",
        "Icelandic" to "isl",
        "Indonesian" to "ind",
        "Inuktitut" to "iku",
        "Irish" to "gle",
        "Italian" to "ita",
        "Japanese" to "jpn",
        "Javanese" to "jav",
        "Kannada" to "kan",
        "Kazakh" to "kaz",
        "Khmer" to "khm",
        "Kinyarwanda" to "kin",
        "Korean" to "kor",
        "Kurdish" to "kur",
        "Lao" to "lao",
        "Latvian" to "lav",
        "Letzeburgesch" to "ltz",
        "Lithuanian" to "lit",
        "Macedonian" to "mkd",
        "Malay" to "msa",
        "Malayalam" to "mal",
        "Maltese" to "mlt",
        "Mandarin Chinese" to "cmn",
        "Marathi" to "mar",
        "Min Nan Chinese" to "nan",
        "Mongolian" to "mon",
        "Nepali" to "nep",
        "Norwegian" to "nor",
        "Norwegian Bokmål" to "nob",
        "Oriya (macrolanguage)" to "ori",
        "Oromo" to "orm",
        "Panjabi" to "pan",
        "Papiamento" to "pap",
        "Pashto" to "pus",
        "Persian" to "fas",
        "Polish" to "pol",
        "Portuguese" to "por",
        "Romanian" to "ron",
        "Romany" to "rom",
        "Russian" to "rus",
        "Serbian" to "srp",
        "Serbo-Croatian" to "hbs",
        "Sindhi" to "snd",
        "Sinhala" to "sin",
        "Slovak" to "slk",
        "Slovenian" to "slv",
        "Somali" to "som",
        "Spanish" to "spa",
        "Swahili" to "swa",
        "Swedish" to "swe",
        "Tagalog" to "tgl",
        "Tajik" to "tgk",
        "Tamil" to "tam",
        "Telugu" to "tel",
        "Tetum" to "tet",
        "Thai" to "tha",
        "Turkish" to "tur",
        "Turkmen" to "tuk",
        "Ukrainian" to "ukr",
        "Urdu" to "urd",
        "Uzbek" to "uzb",
        "Vietnamese" to "vie",
        "Welsh" to "cym",
        "Western Frisian" to "fry",
        "Wolof" to "wol",
        "Yucatec Maya" to "yua",
        "Yue Chinese" to "yue"
    )

    private val countryMap = mapOf(
        "Afghanistan" to "af",
        "Albania" to "al",
        "Algeria" to "dz",
        "Andorra" to "ad",
        "Angola" to "ao",
        "Antigua and Barbuda" to "ag",
        "Argentina" to "ar",
        "Armenia" to "am",
        "Aruba" to "aw",
        "Australia" to "au",
        "Austria" to "at",
        "Azerbaijan" to "az",
        "Bahamas" to "bs",
        "Bahrain" to "bh",
        "Bangladesh" to "bd",
        "Barbados" to "bb",
        "Belarus" to "by",
        "Belgium" to "be",
        "Belize" to "bz",
        "Benin" to "bj",
        "Bolivia" to "bo",
        "Bonaire" to "bq",
        "Bosnia and Herzegovina" to "ba",
        "Botswana" to "bw",
        "Brazil" to "br",
        "British Virgin Islands" to "vg",
        "Brunei" to "bn",
        "Bulgaria" to "bg",
        "Burkina Faso" to "bf",
        "Burundi" to "bi",
        "Cambodia" to "kh",
        "Cameroon" to "cm",
        "Canada" to "ca",
        "Cape Verde" to "cv",
        "Chad" to "td",
        "Chile" to "cl",
        "China" to "cn",
        "Colombia" to "co",
        "Costa Rica" to "cr",
        "Croatia" to "hr",
        "Cuba" to "cu",
        "Curacao" to "cw",
        "Cyprus" to "cy",
        "Czech Republic" to "cz",
        "Democratic Republic of Congo" to "cd",
        "Denmark" to "dk",
        "Djibouti" to "dj",
        "Dominica" to "dm",
        "Dominican Republic" to "do",
        "Ecuador" to "ec",
        "Egypt" to "eg",
        "El Salvador" to "sv",
        "Equatorial Guinea" to "gq",
        "Eritrea" to "er",
        "Estonia" to "ee",
        "Eswatini" to "sz",
        "Ethiopia" to "et",
        "Faroe Islands" to "fo",
        "Fiji" to "fj",
        "Finland" to "fi",
        "France" to "fr",
        "French Polynesia" to "pf",
        "Gabon" to "ga",
        "Gambia" to "gm",
        "Georgia" to "ge",
        "Germany" to "de",
        "Ghana" to "gh",
        "Gibraltar" to "gi",
        "Greece" to "gr",
        "Greenland" to "gl",
        "Grenada" to "gd",
        "Guadeloupe" to "gp",
        "Guam" to "gu",
        "Guatemala" to "gt",
        "Guinea" to "gn",
        "Guinea-Bissau" to "gw",
        "Guyana" to "gy",
        "Haiti" to "ht",
        "Honduras" to "hn",
        "Hong Kong" to "hk",
        "Hungary" to "hu",
        "Iceland" to "is",
        "India" to "in",
        "Indonesia" to "id",
        "Iran" to "ir",
        "Iraq" to "iq",
        "Ireland" to "ie",
        "Israel" to "il",
        "Italy" to "it",
        "Ivory Coast" to "ci",
        "Jamaica" to "jm",
        "Japan" to "jp",
        "Jordan" to "jo",
        "Kazakhstan" to "kz",
        "Kenya" to "ke",
        "Kosovo" to "xk",
        "Kuwait" to "kw",
        "Kyrgyzstan" to "kg",
        "Laos" to "la",
        "Latvia" to "lv",
        "Lebanon" to "lb",
        "Lesotho" to "ls",
        "Liberia" to "lr",
        "Libya" to "ly",
        "Liechtenstein" to "li",
        "Lithuania" to "lt",
        "Luxembourg" to "lu",
        "Macao" to "mo",
        "Madagascar" to "mg",
        "Malawi" to "mw",
        "Malaysia" to "my",
        "Maldives" to "mv",
        "Mali" to "ml",
        "Malta" to "mt",
        "Martinique" to "mq",
        "Mauritania" to "mr",
        "Mauritius" to "mu",
        "Mexico" to "mx",
        "Moldova" to "md",
        "Monaco" to "mc",
        "Mongolia" to "mn",
        "Montenegro" to "me",
        "Montserrat" to "ms",
        "Morocco" to "ma",
        "Mozambique" to "mz",
        "Myanmar" to "mm",
        "Namibia" to "na",
        "Nepal" to "np",
        "Netherlands" to "nl",
        "New Caledonia" to "nc",
        "New Zealand" to "nz",
        "Nicaragua" to "ni",
        "Niger" to "ne",
        "Nigeria" to "ng",
        "North Korea" to "kp",
        "North Macedonia" to "mk",
        "Norway" to "no",
        "Oman" to "om",
        "Pakistan" to "pk",
        "Palestine" to "ps",
        "Panama" to "pa",
        "Papua New Guinea" to "pg",
        "Paraguay" to "py",
        "Peru" to "pe",
        "Philippines" to "ph",
        "Poland" to "pl",
        "Portugal" to "pt",
        "Puerto Rico" to "pr",
        "Qatar" to "qa",
        "Reunion" to "re",
        "Romania" to "ro",
        "Russia" to "ru",
        "Rwanda" to "rw",
        "Saint Kitts and Nevis" to "kn",
        "Saint Lucia" to "lc",
        "Saint Pierre and Miquelon" to "pm",
        "Saint Vincent and the Grenadines" to "vc",
        "Samoa" to "ws",
        "San Marino" to "sm",
        "Sao Tome and Principe" to "st",
        "Saudi Arabia" to "sa",
        "Senegal" to "sn",
        "Serbia" to "rs",
        "Seychelles" to "sc",
        "Sierra Leone" to "sl",
        "Singapore" to "sg",
        "Sint Maarten" to "sx",
        "Slovakia" to "sk",
        "Slovenia" to "si",
        "Solomon Islands" to "sb",
        "Somalia" to "so",
        "South Africa" to "za",
        "South Korea" to "kr",
        "South Sudan" to "ss",
        "Spain" to "es",
        "Sri Lanka" to "lk",
        "Sudan" to "sd",
        "Suriname" to "sr",
        "Sweden" to "se",
        "Switzerland" to "ch",
        "Syria" to "sy",
        "Taiwan" to "tw",
        "Tajikistan" to "tj",
        "Tanzania" to "tz",
        "Thailand" to "th",
        "Timor-Leste" to "tl",
        "Togo" to "tg",
        "Tonga" to "to",
        "Trinidad and Tobago" to "tt",
        "Tunisia" to "tn",
        "Turkey" to "tr",
        "Turkmenistan" to "tm",
        "Uganda" to "ug",
        "Ukraine" to "ua",
        "United Arab Emirates" to "ae",
        "United Kingdom" to "gb",
        "United States" to "us",
        "Uruguay" to "uy",
        "Uzbekistan" to "uz",
        "Vanuatu" to "vu",
        "Vatican City" to "va",
        "Venezuela" to "ve",
        "Vietnam" to "vn",
        "Yemen" to "ye",
        "Zambia" to "zm",
        "Zimbabwe" to "zw"
    )
    
    fun getCategoryUrl(categoryName: String): String {
        val category = categoryMap[categoryName] ?: categoryName.lowercase()
        return UrlBuilder.categories(category)
    }
    
    fun getLanguageUrl(languageName: String): String {
        val code = languageMap[languageName] ?: languageName.lowercase()
        return UrlBuilder.languages(code)
    }

    fun getCountryUrl(countryName: String): String {
        val countryCode = countryMap[countryName] ?: countryName.lowercase()
        return UrlBuilder.countries(countryCode)
    }

    fun isCategory(name: String): Boolean {
        return categoryMap.containsKey(name)
    }
    
    fun isLanguage(name: String): Boolean {
        return languageMap.containsKey(name)
    }
    
    fun isCountry(name: String): Boolean {
        return countryMap.containsKey(name)
    }
}

