package com.ravi.mylivetv.utils

object Constants {
    
    // Tab names
    val TABS = listOf("Categories", "Languages", "Countries")
    
    // Categories list
    val CATEGORIES = listOf(
        "Recently Watched",
        "Movies",
        "Sports",
        "News",
        "Entertainment",
        "Music",
        "Series",
        "Kids",
        "Animation",
        "Business",
        "Comedy",
        "Science",
        "Education",
        "Documentary",
        "Family",
        "Lifestyle",
        "Cooking",
        "Travel",
        "Culture",
        "Outdoor",
        "Weather",
        "Auto",
        "Classic",
        "Religious",
        "Relax",
        "Shop",
        "Legislative",
        "General",
    )
    
    // Languages list
    val LANGUAGES = listOf(
        "Recently Watched",
        // --- Top Indian Priority ---
        "Hindi",
        "English",
        "Bengali",
        "Marathi",
        "Telugu",
        "Tamil",
        "Gujarati",
        "Kannada",
        "Malayalam",
        "Oriya (macrolanguage)",
        "Panjabi",
        "Assamese",
        "Urdu",

        // --- Major Global Languages ---
        "Arabic",
        "Chinese",
        "Mandarin Chinese",
        "Spanish",
        "French",
        "Russian",
        "Japanese",
        "Korean",
        "German",
        "Portuguese",

        // --- Others (Alphabetical) ---
        "Albanian",
        "Amharic",
        "Armenian",
        "Assyrian Neo-Aramaic",
        "Azerbaijani",
        "Bashkir",
        "Basque",
        "Belarusian",
        "Bosnian",
        "Bulgarian",
        "Burmese",
        "Catalan",
        "Croatian",
        "Czech",
        "Danish",
        "Dhivehi",
        "Dimili",
        "Dutch",
        "Estonian",
        "Faroese",
        "Fataleka",
        "Finnish",
        "Galician",
        "Galolen",
        "Georgian",
        "Greek",
        "Greenlandic",
        "Hebrew",
        "Hungarian",
        "Icelandic",
        "Indonesian",
        "Inuktitut",
        "Irish",
        "Italian",
        "Javanese",
        "Kazakh",
        "Khmer",
        "Kinyarwanda",
        "Kurdish",
        "Lao",
        "Latvian",
        "Letzeburgesch",
        "Lithuanian",
        "Macedonian",
        "Malay",
        "Maltese",
        "Min Nan Chinese",
        "Mongolian",
        "Nepali",
        "Norwegian",
        "Norwegian Bokmål",
        "Oromo",
        "Papiamento",
        "Pashto",
        "Persian",
        "Polish",
        "Romanian",
        "Romany",
        "Serbian",
        "Serbo-Croatian",
        "Sindhi",
        "Sinhala",
        "Slovak",
        "Slovenian",
        "Somali",
        "Swahili",
        "Swedish",
        "Tagalog",
        "Tajik",
        "Tetum",
        "Thai",
        "Turkish",
        "Turkmen",
        "Ukrainian",
        "Uzbek",
        "Vietnamese",
        "Welsh",
        "Western Frisian",
        "Wolof",
        "Yucatec Maya",
        "Yue Chinese",
    )
    
    // Countries list
    val COUNTRIES = listOf(
        "Recently Watched",
        // --- Priority 1: Home & Immediate Neighbors ---
        "India",
        "Pakistan",
        "Bangladesh",
        "Nepal",
        "Sri Lanka",
        "Afghanistan",
        "Maldives",

        // --- Priority 2: High Diaspora & Western Content ---
        "United States",
        "United Kingdom",
        "Canada",
        "United Arab Emirates",
        "Australia",
        "Saudi Arabia",
        "Qatar",
        "Kuwait",
        "Singapore",

        // --- Priority 3: Trending Content (K-Drama, Turkish Drama, Global) ---
        "South Korea",
        "Turkey",
        "Japan",
        "Germany",
        "France",
        "Russia",
        "Israel",
        "China",

        // --- Others (Alphabetical for easier searching) ---
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bolivia",
        "Bonaire",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "British Virgin Islands",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Cape Verde",
        "Chad",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Curacao",
        "Cyprus",
        "Czech Republic",
        "Democratic Republic of Congo",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "French Polynesia",
        "Gabon",
        "Gambia",
        "Georgia",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Italy",
        "Ivory Coast",
        "Jamaica",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kosovo",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Mali",
        "Malta",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Netherlands",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Korea",
        "North Macedonia",
        "Norway",
        "Oman",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Reunion",
        "Romania",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Sint Maarten",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Spain",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkmenistan",
        "Uganda",
        "Ukraine",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    )
}



